[platformio]
default_envs = cyd
description = RetroTape-ESP32-CYD

[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = chain+
lib_deps =
  lovyan03/LovyanGFX@^1.2.7
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DRETROTAPE_BOARD_CYD
  -DCORE_DEBUG_LEVEL=3
